services:
    # PHP Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8000:8000
        depends_on:
            - mysql
        networks:
            - mytripcost-net

    # db mysql
    mysql:
        image: mysql
        container_name: mytripcost-mysql
        #restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mysql
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        ports:
            - ${DB_PORT}:${DB_PORT}
        networks:
            - mytripcost-net

    # nginx
    nginx:
        image: nginx:alpine
        container_name: mytripcost-nginx
        restart: unless-stopped
        ports:
            - "8989:89"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - mytripcost-net

networks:
  mytripcost-net:
    driver: bridge
