name: html.mytripcost.api deployment

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout no repositorio
              run: echo building the app web

    deploy-homologacao:
        runs-on: ubuntu-latest
        environment:
            name: homologacao
            url: 'hmlapi.mytripcost.com.br'
        steps:
            - name: Repo checkout
              uses: actions/checkout@v2
            - name: Deploy para o desenvolvimento HML
              uses: SamKirkland/FTP-Deploy-Action@4.0.0
              with:
                server: ${{ secrets.FTP_HOST }}
                username: ${{ secrets.FTP_USER }}
                password: ${{ secrets.FTP_PASSWORD }}
                server-dir: ${{vars.REMOTE_TARGET_HML}}
            - name: Install Composer dependencies
              run: composer install --prefer-dist --no-interaction --no-suggest